webmonitors/webapp/urls.py
# -*- coding:UTF-8 -*-

from django.conf.urls import url
from . import views

app_name = 'webapp'

urlpatterns = [
    # url(r'^$', views.index, name='index'),
    # url(r'^login/$', views.login, name='login'),
    url(r'^$', views.login, name='login'),
    url(r'^index/$', views.index, name='index'),
    url(r'^checkuser/$', views.checkuser, name='checkuser'),
    url(r'^verifycode/$', views.verifycode, name='verifycode'),
    url(r'^add/$', views.add, name='add'),
    url(r'^list/$', views.list, name='list'),
    url(r'^find/$', views.find, name='find'),
    url(r'^mail/$', views.mail, name='mail'),
    url(r'^send/$', views.send, name='send'),
    url(r'^result/$', views.result, name='result'),
]

webmonitors/webmonitors/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import url, include

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('webapp/', include('webapp.urls', namespace='webapp')),
]

webmonitors/webapp/models.py
# -*- coding:UTF-8 -*-

from django.db import models

# Create your models here.


# 主机表
class Host_info(models.Model):
    app_name = models.CharField(max_length=40)
    url = models.CharField(max_length=100)
    idc = models.CharField(max_length=4)
    alarm_type = models.CharField(max_length=8)
    alarm_info = models.CharField(max_length=30)

    def __str__(self):
        return self.app_name


# 监控数据表
class Monitor_data(models.Model):
    fid = models.ForeignKey('Host_info', on_delete=models.CASCADE)
    dns_lookup_time = models.FloatField()
    connect_time = models.FloatField()
    pre_transfer_time = models.FloatField()
    start_transfer_time = models.FloatField()
    total_time = models.FloatField()
    http_status = models.CharField(max_length=100)
    size_download = models.FloatField()
    size_header = models.SmallIntegerField()
    size_request = models.SmallIntegerField()
    download_length = models.FloatField()
    download_speed = models.FloatField()
    datetime = models.DateTimeField(auto_now_add=True, max_length=12)
    mark = models.IntegerField(default=0)

    def __str__(self):
        return "FID: "+str(self.fid.id)

webmonitors/webapp/views.py
# -*- coding:UTF-8 -*-

from django.shortcuts import render, redirect, reverse
from django.http import HttpResponse
from django.conf import settings
from .models import *
import time, pycurl, random, io
from . import webprobe
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from PIL import Image, ImageFont, ImageDraw
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.core.mail import send_mail, send_mass_mail

from publicapp.views import *

# Create your views here.


def index(request):
    # return render(request, 'webapp/index.html')
    system_name = settings.SYSTEM_NAME
    host_info_obj = Host_info.objects.order_by('app_name')

    if authenticate(username=request.session.get('name'), password=request.session.get('pass')):
        if request.method == 'GET':
            return render(request, 'webapp/index.html', {'sys_name': system_name, 'host_info_obj': host_info_obj})
        elif request.method == 'POST':
            if request.POST['app_id']:
                # print("+++++++++++++++")
                # print(request.POST)
                # return HttpResponse("post请求")
                try:
                    app_id = request.POST['app_id']
                    host_info_row = Host_info.objects.filter(id=app_id)[0]
                    # print (host_info_row.url)
                    webprobe.probe(host_info_row.url, app_id)
                    if not 'start_time' in request.POST or request.POST['start_time'] == '':
                        start_time = int(str(time.time()).split('.')[0]) - 86400 * 3
                        end_time = int(str(time.time()).split('.')[0])
                        user_find = '0'
                        print("-------------")
                        result = Graphrrd_normal(host_info_row.id, host_info_row.url, host_info_row.app_name)
                        # print (result, type(result))
                    else:
                        # start_time = int(time.mktime(time.strptime(request.POST['start_time'], '%Y-%m-%d %H:%M:%S')))
                        start_time = request.POST['start_time']
                        # end_time = int(time.mktime(time.strptime(request.POST['end_time'], '%Y-%m-%d %H:%M:%S')))
                        end_time = request.POST['end_time']
                        # print(start_time, end_time)
                        user_find = '1'
                        print("+++++++++++++")
                        try:
                            # r = 5 / 1
                            result = Graphrrd_custom(host_info_row.id, start_time, end_time, host_info_row.url, host_info_row.app_name)
                        except Exception as e:
                            info = ['系统提示：', '图型绘制失败,原因(' + str(e) + ')', '/webapp/index']
                            return render(request, 'webapp/error.html', {'show_info': info})
                    return render(request, 'webapp/index.html', {'sys_name': system_name, 'host_info_obj': host_info_obj,
                                                             'host_info_row': host_info_row, 'start_time': start_time,
                                                             'end_time': end_time, 'user_find': user_find, 'url': str(result['url']),
                                                                 'num': str(result['num'])})
                except Exception as e:
                    info = ['系统提示：', str(e), '/webapp/index']
                    return render(request, 'webapp/error.html', {'show_info': info})
            else:
                print("======================>None")
                info = ['系统提示：', '未选择任何业务', '/webapp/index']
                return render(request, 'webapp/error.html', {'show_info': info})
    else:
        return redirect(reverse('webapp:login'))


def add(request):
    idc_str = ""
    for k, v in settings.IDC.items():
        idc_str += "<input name='idc' type='checkbox' value=" + k + " id=" + k + "/>" + v + "\n"
    if request.method == 'GET':
        return render(request, 'webapp/add.html', {'IDC': idc_str})
    elif request.method == 'POST':
        appname = request.POST['appname']
        appurl = request.POST['appurl']
        hotice = request.POST['hotice']
        status = request.POST['status']
        responsechar = request.POST['responsechar']
        if responsechar:
            temp = responsechar
        else:
            temp = status
        if 'idc' in request.POST:
            idc = request.POST['idc']
            host_info_dict = {'app_name': appname, 'url': appurl, 'idc': idc, 'alarm_type': hotice, 'alarm_info': temp}
            try:
                host = Host_info.objects.create(**host_info_dict)
                # print(host)
                # return redirect(reverse('webapp:index'))

                try:
                    if not os.path.isdir(settings.RRD_PATH + '/' + GetURLdomain(appurl)):
                        os.makedirs(settings.RRD_PATH + '/' + GetURLdomain(appurl))

                    if not os.path.isdir(settings.PNG_PATH + '/' + GetURLdomain(appurl)):
                        os.makedirs(settings.PNG_PATH + '/' + GetURLdomain(appurl))

                except Exception as e:
                    return HttpResponse("目录创建失败！" + str(e))

                try:
                    create_rrd(str(appurl))
                except Exception as e:
                    return HttpResponse("目录RRD文件失败！" + str(e))

                info = ['系统提示：', '祝贺你，应用添加成功！请返回', '/webapp/index']
                return render(request, 'webapp/error.html', {'show_info': info})
            except Exception as e:
                info = ['系统提示：', e, '/webapp/index']
                return render(request, 'webapp/error.html', {'show_info': info})

        else:
            info = ['系统提示：', '探测点不能为空', '/webapp/index']
            return render(request, 'webapp/error.html', {'show_info': info})


def list(request):
    try:
        app_id = request.GET['app_id']
        start_time = request.GET['start_time']
        end_time = request.GET['end_time']
        # print(app_id, start_time, end_time)
        # print(type(Monitor_data.objects.filter(fid=app_id)[0]))
        # contact_list = Monitor_data.objects.filter(fid=app_id).filter(datetime__gte=start_time).filter(datetime__lte=end_time).order_by("-datetime")
        contact_list = Monitor_data.objects.filter(fid=app_id).order_by("-datetime")
        # print("====================>", contact_list)
        # 分页
        pageinator = Paginator(contact_list, 5)
        num = request.GET.get('page')
        try:
            page = pageinator.page(num)
        except PageNotAnInteger:
            page = pageinator.page(1)
        except EmptyPage:
            page = pageinator.page(pageinator.num_pages)

        return render(request, 'webapp/list.html', {'pages': page, 'app_id':app_id,'start_time':start_time,'end_time':end_time})
    except Exception as e:
        return render(request, 'webapp/list.html')


def login(request):
    if request.method == 'POST':
        try:
            username = request.POST['username']
            password = request.POST['password']
            request.session['name'] = username
            request.session['pass'] = password
            request.session.set_expiry(3600)
            verify = request.POST['verify'].lower()
            verifycode = request.session.get('verifycode').lower()

            if verify == verifycode:
                if authenticate(username=request.session.get('name'), password=request.session.get('pass')):
                    return redirect(reverse('webapp:index'))
                else:
                    return redirect(reverse('webapp:login'))
            else:
                print ("验证码错误")
                return render(request, 'webapp/login.html')
        except Exception as e:
            print (e)

    return render(request, 'webapp/login.html')


def checkuser(request):
    if request.method == 'POST':
        username = request.POST['username']
        user = User.objects.filter(username=username).first()
        if user is None:
            return HttpResponse("用户名错误")
        else:
            return HttpResponse("accept")


def verifycode(request):
    # 生成一张验证码图片
    # 定义变量，用于画面的背景色、宽、高
    bgcolor = (random.randrange(20, 100), random.randrange(20, 100), random.randrange(20, 100))
    width = 93
    heigth = 50
    # 创建画面对象
    im = Image.new('RGB', (width, heigth), bgcolor)
    # 创建画笔对象
    draw = ImageDraw.Draw(im)
    # 调用画笔的point()函数绘制噪点
    for i in range(0, 100):
        xy = (random.randrange(0, width), random.randrange(0, heigth))
        fill = (random.randrange(0, 255), 255, random.randrange(0, 255))
        draw.point(xy, fill=fill)
    # 定义验证码的备选值
    str1 = 'ABCD123EFGHIJK456LMNOPQRS789TUVWXYZ0'
    # 随机选取4个值作为验证码
    rand_str = ''
    for i in range(0, 4):
        rand_str += str1[random.randrange(0, len(str1))]
    # 构造字体对象
    # font = ImageFont.truetype('SCRIPTBL.TTF', 23)
    font = ImageFont.truetype('/usr/share/fonts/MAGNETOB.TTF', 24)
    fontcolor = (255, random.randrange(0, 255), random.randrange(0, 255))
    # 绘制4个字
    draw.text((5, 13), rand_str[0], font=font, fill=fontcolor)
    draw.text((25, 13), rand_str[1], font=font, fill=fontcolor)
    draw.text((50, 13), rand_str[2], font=font, fill=fontcolor)
    draw.text((75, 13), rand_str[3], font=font, fill=fontcolor)

    # 释放画笔
    del draw
    # 将生成的验证码存入session
    request.session['verifycode'] = rand_str
    print(rand_str)
    f = io.BytesIO()
    im.save(f, 'png')
    # 将内存中的图片数据返回给客户端，MIME类型为图片png
    return HttpResponse(f.getvalue(), 'image/png')


def find(request):

    if request.method == 'GET':
        return render(request, 'webapp/verifyuser.html')
    elif request.method == 'POST':
        try:
            username = request.POST['username']
            verify = request.POST['code'].lower()
            verifycode = request.session.get('verifycode').lower()

            if verify == verifycode:

webmonitors/templates/webapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} 基础模板页 {% endblock %}</title>
    <!-- CSS样式 -->
    {% load static from staticfiles %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    {% block link_css %}{% endblock %}
    <!-- JavaScript代码控制 -->
    <script src="{% static 'js/jquery-2.1.4.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
    {% block link_js %}{% endblock %}

</head>
<body>
    <div class="container">
        <div class="row title">
            <div class="col-md-12"><h2>业务质量监控</h2></div>
        </div>
    </div>
    {% block body %}{% endblock %}
</body>
</html>

webmonitors/templates/webapp/error.html
{% extends 'webapp/base.html' %}
{%  block title %}系统信息提示{% endblock %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="title col-md-push-4 col-md-4"> <h4 style="width: 410px; background-color: #cccccc; color: white; padding: 10px; border-radius: 5px;">>>{{ show_info.0 }}</h4> </div>
        </div>
        <div class="row">
            <div class="info col-md-push-4 col-md-4">
                <textarea name="" id="" cols="50" rows="10" readonly style="border-radius: 5px;">{{ show_info.1 }}</textarea>
                <div class="back col-md-push-5 col-md-4" style="margin-left: 25px;">
                    「<a href="{{ show_info.2 }}">返回</a>」
                </div>
            </div>
        </div>
    </div>

{% endblock %}

webmonitors/templates/webapp/index.html
{% extends 'webapp/base.html' %}
{% block title %}主页{% endblock %}

{% block link_css %}
    {% load static from staticfiles %}
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
{% endblock %}


{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-push-1">
                <div class="content">
                    <div class="forms">
                        <form action="{% url 'webapp:index' %}" method="post">
                            {% csrf_token %}
                            <span style="margin-right: 20px"></span>
                            选择业务：
                            <select name="app_id" id="app_id" style="margin-right: 50px">
                                {% for h in host_info_obj %}
                                    <option value="{{h.id}}"> {{ h.app_name }} </option>
                                {% empty %}
                                    <option value=""> NULL </option>
                                {% endfor %}
                            </select>
                            <!--起始时间：<input type="datetime-local" name="start_time" id="start_time" onfocus="WdatePicker({skin:'whyGreen',dateFmt:'yyyy-MM-dd HH:mm:ss',minDate:'2010-11-18 00:00:00'})">-->
                            起始时间：<input type="datetime-local" name="start_time" id="start_time">
                            <!--结束时间：<input type="datetime-local" name="end_time" id="end_time" onfocus="WdatePicker({skin:'whyGreen',dateFmt:'yyyy-MM-dd HH:mm:ss',minDate:'2010-11-18 00:00:00'})">&nbsp;&nbsp;-->
                            结束时间：<input type="datetime-local" name="end_time" id="end_time">&nbsp;&nbsp;
                            <input type="submit" value="提交">
                            <a href="{% url 'webapp:add' %}">添加应用</a>
                        </form>
                     </div>
                    <div class="bottom">
                        {% if host_info_row %}
                            {% ifequal user_find '1' %}
                                <div class="bottom_title">

                                    <img src="{% static 'img/chart.png' %}" alt="图片加载失败">
                                    <h5>{{ host_info_row.app_name }} - <span>监测数据图表</span><span>[自定义]</span></h5>

                                </div>

                                <div class="bottom_body">

                                    <div class="child_left" style="width: 60%; float: left">
                                        <img src="/static/rrdtool/{{url}}/{{num}}_time.png" alt="图片加载失败">
                                    </div>
                                    <div class="child_right" style="width: 40%; float: left;">

                                        <div class="child_right_up">
                                            <img src="/static/rrdtool/{{url}}/{{num}}_download.png" alt="图片加载失败">
                                        </div>
                                        <div class="child_right_down">
                                            <img src="/static/rrdtool/{{url}}/{{num}}_unavailable.png" alt="图片加载失败">
                                        </div>

                                    </div>

                                </div>
                            {% else %}
                                <div class="bottom_title">

                                    <img src="{% static 'img/chart.png' %}" alt="图片加载失败">
                                    <h5>{{ host_info_row.app_name }} - <span>监测数据图表</span><span>[当前]</span></h5>

                                </div>

                                <div class="bottom_body">

                                    <div class="child_left" style="width: 60%; float: left">
                                        <img src="/static/rrdtool/{{url}}/current_{{num}}_time.png" alt="图片加载失败">
                                    </div>
                                    <div class="child_right" style="width: 40%; float: left;">

                                        <div class="child_right_up">
                                            <img src="/static/rrdtool/{{url}}/current_{{num}}_download.png" alt="图片加载失败">
                                        </div>
                                        <div class="child_right_down">
                                            <img src="/static/rrdtool/{{url}}/current_{{num}}_unavailable.png" alt="图片加载失败">
                                        </div>

                                    </div>

                                </div>

                                <div class="bottom_title update">

                                    <img src="{% static 'img/chart.png' %}" alt="图片加载失败">
                                    <h5>{{ host_info_row.app_name }} - <span>监测数据图表</span><span>[日]</span></h5>

                                </div>

                                <div class="bottom_body">

                                    <div class="child_left" style="width: 60%; float: left">
                                        <img src="/static/rrdtool/{{url}}/day_{{num}}_time.png" alt="图片加载失败">
                                    </div>
                                    <div class="child_right" style="width: 40%; float: left;">

                                        <div class="child_right_up">
                                            <img src="/static/rrdtool/{{url}}/day_{{num}}_download.png" alt="图片加载失败">
                                        </div>
                                        <div class="child_right_down">
                                            <img src="/static/rrdtool/{{url}}/day_{{num}}_unavailable.png" alt="图片加载失败">
                                        </div>

                                    </div>

                                </div>

                                <div class="bottom_title update">

                                    <img src="{% static 'img/chart.png' %}" alt="图片加载失败">
                                    <h5>{{ host_info_row.app_name }} - <span>监测数据图表</span><span>[月]</span></h5>

                                </div>

                                <div class="bottom_body">

                                    <div class="child_left" style="width: 60%; float: left">
                                        <img src="/static/rrdtool/{{url}}/month_{{num}}_time.png" alt="图片加载失败">
                                    </div>
                                    <div class="child_right" style="width: 40%; float: left;">

                                        <div class="child_right_up">
                                            <img src="/static/rrdtool/{{url}}/month_{{num}}_download.png" alt="图片加载失败">
                                        </div>
                                        <div class="child_right_down">
                                            <img src="/static/rrdtool/{{url}}/month_{{num}}_unavailable.png" alt="图片加载失败">
                                        </div>

                                    </div>

                                </div>

                                <div class="bottom_title update">

                                    <img src="{% static 'img/chart.png' %}" alt="图片加载失败">
                                    <h5>{{ host_info_row.app_name }} - <span>监测数据图表</span><span>[年]</span></h5>

                                </div>

                                <div class="bottom_body">

                                    <div class="child_left" style="width: 60%; float: left">
                                        <img src="/static/rrdtool/{{url}}/year_{{num}}_time.png" alt="图片加载失败">
                                    </div>
                                    <div class="child_right" style="width: 40%; float: left;">

                                        <div class="child_right_up">
                                            <img src="/static/rrdtool/{{url}}/year_{{num}}_download.png" alt="图片加载失败">
                                        </div>
                                        <div class="child_right_down">
                                            <img src="/static/rrdtool/{{url}}/year_{{num}}_unavailable.png" alt="图片加载失败">
                                        </div>

                                    </div>

                                </div>

                            {% endifequal %}
                            <div class="applist">
                                <iframe src="{% url 'webapp:list'%}?app_id={{ host_info_row.id }}&start_time={{ start_time }}&end_time={{ end_time }} " frameborder="1" width="100%" height="300px" style="padding: 2px"></iframe>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

webmonitors/templates/webapp/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登录</title>

    {% load static from staticfiles %}
    <link rel="stylesheet" href="{% static 'css/login.css' %}">

    <script src="{% static 'js/jquery-2.1.4.js' %}"></script>
    <script>

        $(function () {
            $('#username').blur(function () {
                console.log("+++")
                $.ajax({
                    url: '/webapp/checkuser/',
                    type: 'post',
                    data: {
                        "csrfmiddlewaretoken": $("input[name=csrfmiddlewaretoken]").val(),
                        "username": $("#username").val()
                    },
                    success: function (data) {
                        console.log("+++")
                        console.log(data)
                        $('#userinfo').text(data);
                    }
                })
            })

            $('#verifycode').click(function () {
                t = new Date()
                this.src = '/webapp/verifycode/?t='+t.getTime()
            })
        })

    </script>

</head>
<body>

    <div class="container">
        <div class="row">
            <img src="{% static 'img/dl_01.png' %}" alt="">
            <div class="row_login">
                <dl>

                    <form action="{% url 'webapp:login' %}" method="post">

                        {% csrf_token %}

                        <dt><h1>登录</h1></dt>
                        <dd>
                            <input type="text" name="username" id="username" placeholder="用户名/手机号" required> <span id="userinfo" style="position: fixed; margin-left: 5px;line-height: 50px"></span>
                        </dd>
                        <dd>
                            <input type="password" name="password" id="password" placeholder="密码" required>
                        </dd>
                        <dd>
                            <input type="text" name="verify" placeholder="验证码" required />
                            <a href="#"><img src="{% url 'webapp:verifycode' %}" alt="验证码加载失败" id="verifycode"></a>
                        </dd>
                        <dd>
                            <button type="submit">立即登录</button>
                        </dd>
                        <dd>
                            <a href="{% url 'webapp:find' %}" id="find_pass">忘记密码？<span>点击找回</span></a>
                        </dd>

                    </form>

                </dl>
            </div>
        </div>
    </div>

</body>
</html>

webmonitors/templates/webapp/sendmail.html
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>邮箱验证</title>

    {% load static from staticfiles %}

    <link rel="stylesheet" href="{% static 'css/jcss.css' %}">
    <link rel="stylesheet" href="{% static 'css/ny.css' %}">

    <script src="{% static 'js/jquery-2.1.4.js' %}"></script>
    <script>

        $(function () {

            $('#verifycode').click(function () {
                t = new Date()
                this.src = '/webapp/verifycode/?t='+t.getTime()
            })
        })

    </script>

</head>

<body>


    <div class="J-forgetpassword nav-con jboxsize jborder">
        <ol>
            <li>1 填写账号信息</li>
            <li class="J-current">2 验证邮箱信息</li>
            <li>3 邮件投递</li>
            <li style="border:none;">4 成功</li>
            <div class="jclear"></div>
        </ol>
        <div class="clear"></div>
        <ul>
            <form action="{% url 'webapp:mail' %}" method="post">
            <li>
                <div class="J-fg-list clearfix J-fg-yzzh" style="position:relative;">
                    {% csrf_token %}
                    <input type="text" name="username" value="{{username}}" hidden>
                    <p>填写邮箱</p>
                    <input class="cyyj_in_hover" type="email" id="useremail" name="useremail" placeholder="邮箱账号" required/>
                    <i class="sl_bdyh"> <a href="#">使用邮箱找回</a></i>
                </div>
            </li>
          
            <li>
                <div class="J-fg-list clearfix">
                    <p style="width:29%;">验证码</p>
                    <input style="width:40%; margin-right:5px;" type="text" id="code" name="code" placeholder="验证码" required/>
                    <a href="#"><img src="{% url 'webapp:verifycode' %}" alt="验证码加载失败" id="verifycode"></a>
                </div>
              <!--<div class="clear"></div>-->
              <!--<p class="rci_prompt text-overflow J-fg-ml">验证码错误</p>-->
            </li>
            <li>
                <div class="J-fg-list clearfix">
                    <p style="width:29%;">&nbsp;</p>
                    <div class="J-btn jfl jmt25" style="width:71%;"><input type="submit" value="发送" style="width:100%;font-weight:bold;background-color: #EEEEEE;"/></div>
                    <div class="J-btn jfl jmt25" style="width:71%;float: right;"><a href="{% url 'webapp:find' %}" style="width:100%;font-weight:bold;">上一步</a></div>
                </div>`
            </li>
            </form>
        </ul>
    </div>



</body>
</html>

webmonitors/templates/webapp/verifyuser.html
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>填写账户信息</title>

    {% load static from staticfiles %}
    <link rel="stylesheet" href="{% static 'css/jcss.css' %}">
    <link rel="stylesheet" href="{% static 'css/ny.css' %}">

    <script src="{% static 'js/jquery-2.1.4.js' %}"></script>
    <script>

        $(function () {
            $('#username').blur(function () {
                console.log("+++")
                $.ajax({
                    url: '/webapp/checkuser/',
                    type: 'post',
                    data: {
                        "csrfmiddlewaretoken": $("input[name=csrfmiddlewaretoken]").val(),
                        "username": $("#username").val()
                    },
                    success: function (data) {
                        console.log("+++")
                        console.log(data)
                        $('#userinfo').text(data);
                    }
                })
            })

            $('#verifycode').click(function () {
                t = new Date()
                this.src = '/webapp/verifycode/?t='+t.getTime()
            })
        })

    </script>

</head>

<body>

    <div class="J-forgetpassword nav-con jboxsize jborder">
        
         <ol class="sl_txzh">
             <li class="J-current">1 填写账号信息</li>
             <li>2 验证邮箱信息</li>
             <li>3 邮件投递</li>
             <li style="border:none;">4 成功</li>
             <div class="jclear"></div>
         </ol>
         <ul>
             <form action="{% url 'webapp:find' %}" method="post">
             <li>
                 <div class="J-fg-list clearfix">
                    {% csrf_token %}
                    <p>账户</p>
                    <input class="cyyj_in_hover" type="text" id="username" name="username" placeholder="账户/用户名" required/>
                 </div>
                 <div class="clear"></div>
                 <p class="rci_prompt text-overflow J-fg-textindent" id="userinfo"></p>
             </li>
             <li>
                 <div class="J-fg-list clearfix">
                     <p>验证码</p>
                     <input style="width:50%; margin-right:5px;" type="text" id="code" name="code" placeholder="验证码" required/>
                     <span><a href="#"><img src="{% url 'webapp:verifycode' %}" alt="验证码加载失败" id="verifycode"></a></span>
                 </div>
              <!--<div class="clear"></div>-->
              <!--<p class="rci_prompt text-overflow J-fg-textindent">验证码错误</p>-->
             </li>
             <li>
                 <div class="J-fg-list clearfix">
                     <p>&nbsp;</p>
                     <div class="J-btn jfl jmt25" style="width:80%;"><input type="submit" value="下一步" style="width: 100%;background-color: #EEEEEE;"/></div>
                     <div class="J-btn jfl jmt25" style="width:80%;float: right;margin-right: 1%;"><a href="{% url 'webapp:login' %}" style="width:100%;">返回登录</a></div>
                 </div>`
             </li>
             </form>
         </ul>
    </div>

</body>
</html>